# Site settings
title:       Tim Potter
email:       tpot@frungy.org
author:      Tim Potter
description: "Software engineer and open source technologist."
baseurl:     ""
url:         "http://frungy.org"

# Google analytics
google_analytics: UA-16443460-1

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: tpot
stackoverflow_id: 61085
twitter_username: timothypotter
google_plus_id:
linkedin_username: timothymartinpotter
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
gems: [jekyll-paginate]
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:categories/:title
paginate:     3
sass:
  compressed: true
